id: c984396144364679a8646547c7c519bd
initial_creation_type: ocr
source_metadata:
  volumes:
    6e941450ebfe4f788881fa9a17c61086:
      base_file: v057.txt
      image_group_id: I1PD95903
      title: དབུ་མའི་སྙིང་པོའི་འགྲེལ་པ་རྟོག་གེ་འབར་བ།
      total_pages: 1649
      volume_number: 58
